# Generated by Django 6.0.7 on 2026-07-10 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup_type', models.CharField(choices=[('manual', 'Вручную'), ('auto', 'Авто')], max_length=10)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='storage.storedfile')),
            ],
            options={
                'verbose_name': 'Резервная копия',
                'verbose_name_plural': 'Резервные копии',
                'ordering': ['-created_at'],
            },
        ),
    ]
