# Generated by Django 6.0.7 on 2026-07-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_full_backups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupdestinationstatus',
            name='destination',
            field=models.CharField(choices=[('own', 'Хранилище приложения'), ('secondary_s3', 'Отдельный S3 для бэкапов')], max_length=16),
        ),
    ]
