# Generated by Django 6.0.7 on 2026-07-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_maintain',
            field=models.BooleanField(default=False, verbose_name='Ответственный за регламенты и проведение ТО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('accountant', 'Ответственный за учёт'), ('maintenance', 'Ответственный за ТО'), ('employee', 'Сотрудник')], default='employee', max_length=20, verbose_name='Уровень доступа'),
        ),
    ]
