# Generated by Django 6.0.7 on 2026-07-22 05:08

from django.db import migrations, models


def backfill_manage_regulations(apps, schema_editor):
    # B23: до этого релиза единый флаг can_maintain у «Ответственного за учёт»
    # давал и проведение ТО, и управление регламентами. Разделяем: существующим
    # accountant с can_maintain=True проставляем и can_manage_regulations=True,
    # чтобы не потерять возможность управлять регламентами (can_maintain остаётся
    # как «проведение ТО»). maintenance_all_types по умолчанию True — все, кто
    # проводил ТО, продолжают видеть все типы.
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="accountant", can_maintain=True).update(can_manage_regulations=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_can_maintain_alter_user_role'),
        ('equipment', '0017_equipmenttype_allows_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_regulations',
            field=models.BooleanField(default=False, verbose_name='Может управлять регламентами ТО'),
        ),
        migrations.AddField(
            model_name='user',
            name='maintenance_all_types',
            field=models.BooleanField(default=True, verbose_name='ТО по всем типам оборудования'),
        ),
        migrations.AddField(
            model_name='user',
            name='maintenance_types',
            field=models.ManyToManyField(blank=True, related_name='maintainer_users', to='equipment.equipmenttype', verbose_name='Типы оборудования для ТО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_maintain',
            field=models.BooleanField(default=False, verbose_name='Ответственный за ТО'),
        ),
        migrations.RunPython(backfill_manage_regulations, migrations.RunPython.noop),
    ]
