# Generated by Django 6.0.7 on 2026-07-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_strip_superuser_b9'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_maintain_transport',
            field=models.BooleanField(default=False, verbose_name='Ответственный за ТО Транспорта'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_transport_regulations',
            field=models.BooleanField(default=False, verbose_name='Может управлять регламентами ТО Транспорта'),
        ),
        migrations.AddField(
            model_name='user',
            name='maintenance_all_transport_types',
            field=models.BooleanField(default=True, verbose_name='ТО по всем типам транспорта'),
        ),
    ]
