# Generated by Django 6.0.7 on 2026-07-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_can_maintain_transport_and_more'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maintenance_transport_types',
            field=models.ManyToManyField(blank=True, related_name='maintainer_users', to='transport.transporttype', verbose_name='Типы транспорта для ТО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_maintain',
            field=models.BooleanField(default=False, verbose_name='Ответственный за ТО Оборудования'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_manage_regulations',
            field=models.BooleanField(default=False, verbose_name='Может управлять регламентами ТО Оборудования'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('accountant', 'Ответственный за учёт'), ('maintenance', 'Механик по оборудованию'), ('automechanic', 'Автомеханик'), ('employee', 'Сотрудник')], default='employee', max_length=20, verbose_name='Уровень доступа'),
        ),
    ]
