# Generated by Django 6.0.7 on 2026-07-29 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_maintenance_transport_types_and_more'),
        ('equipment', '0018_alter_equipmentcustomfield_options_and_more'),
        ('transport', '0002_historicaltransport_parks_at_driver_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceReminderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_kind', models.CharField(choices=[('equipment', 'Оборудование'), ('transport', 'Транспорт')], max_length=16)),
                ('plan_id', models.PositiveIntegerField()),
                ('notified_status', models.CharField(blank=True, max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan_kind', 'plan_id'), name='uniq_maint_reminder_plan')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True, verbose_name='Endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='Ключ p256dh')),
                ('auth', models.CharField(max_length=255, verbose_name='Ключ auth')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push-подписка',
                'verbose_name_plural': 'Push-подписки',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('assignment_pending', 'Закрепление нового имущества'), ('maintenance_due', 'Подходящее ТО'), ('maintenance_overdue', 'Просроченное ТО'), ('maintenance_performed', 'Выполненное ТО')], max_length=32, verbose_name='Вид уведомления')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Почта')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push')),
                ('equipment_all_types', models.BooleanField(default=True, verbose_name='Все типы оборудования')),
                ('transport_all_types', models.BooleanField(default=True, verbose_name='Все типы транспорта')),
                ('equipment_types', models.ManyToManyField(blank=True, related_name='notification_prefs', to='equipment.equipmenttype', verbose_name='Типы оборудования')),
                ('transport_types', models.ManyToManyField(blank=True, related_name='notification_prefs', to='transport.transporttype', verbose_name='Типы транспорта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройка уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
                'constraints': [models.UniqueConstraint(fields=('user', 'kind'), name='uniq_notif_pref_user_kind')],
            },
        ),
    ]
