# Generated by Django 6.0.7 on 2026-08-12 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_notificationpreference_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('push', 'Push'), ('email', 'Email')], max_length=8)),
                ('kind', models.CharField(blank=True, max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отложенное уведомление',
                'verbose_name_plural': 'Отложенные уведомления',
                'ordering': ['scheduled_for', 'id'],
            },
        ),
    ]
