# Generated by Django 6.0.7 on 2026-07-10 19:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивный')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=255, verbose_name='Учётный номер')),
                ('is_written_off', models.BooleanField(default=False, verbose_name='Признак списания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='employees.employee', verbose_name='Сотрудник')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.equipmenttype', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Дополнительное поле оборудования',
                'verbose_name_plural': 'Дополнительные поля оборудования',
            },
        ),
        migrations.CreateModel(
            name='EquipmentTypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование реквизита')),
                ('value_type', models.CharField(choices=[('bool', 'Булево'), ('text', 'Текст'), ('int', 'Целое число'), ('float', 'Дробное число'), ('file', 'Файл')], max_length=10, verbose_name='Значение типа')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательность')),
                ('is_locked', models.BooleanField(default=False)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='equipment.equipmenttype')),
            ],
            options={
                'verbose_name': 'Реквизит типа оборудования',
                'verbose_name_plural': 'Реквизиты типа оборудования',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEquipment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=255, verbose_name='Учётный номер')),
                ('is_written_off', models.BooleanField(default=False, verbose_name='Признак списания')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee', verbose_name='Сотрудник')),
                ('equipment_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.equipmenttype', verbose_name='Тип оборудования')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Оборудование',
                'verbose_name_plural': 'historical Оборудование',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EquipmentFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to='equipment/fields/')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='equipment.equipment')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='equipment.equipmenttypefield')),
            ],
            options={
                'verbose_name': 'Значение реквизита оборудования',
                'verbose_name_plural': 'Значения реквизитов оборудования',
                'constraints': [models.UniqueConstraint(fields=('equipment', 'field'), name='uniq_equipment_field_value')],
            },
        ),
    ]
