# Generated by Django 6.0.7 on 2026-07-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipmentfieldvalue_value_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='written_off_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата списания'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='written_off_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата списания'),
        ),
    ]
