# Generated by Django 6.0.7 on 2026-07-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_uniq_equipment_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalequipment',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalequipmentcustomfield',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalequipmentfieldfile',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalequipmentfieldvalue',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
