# Generated by Django 6.0.7 on 2026-07-19 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_accesspass_uniq_pass_account_by_type'),
        ('equipment', '0007_alter_historicalequipment_history_change_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='accounting_type',
            field=models.CharField(choices=[('instance', 'Поэкземплярный'), ('quantity', 'Количественный')], default='instance', max_length=10, verbose_name='Вид учёта'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток'),
        ),
        migrations.CreateModel(
            name='EquipmentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('add', 'Приход'), ('write_off', 'Списание'), ('assign', 'Закрепление'), ('unassign', 'Открепление')], max_length=10, verbose_name='Тип движения')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee', verbose_name='Сотрудник')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Движение количественного оборудования',
                'verbose_name_plural': 'Движения количественного оборудования',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_allocations', to='employees.employee', verbose_name='Сотрудник')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Закрепление количественного оборудования',
                'verbose_name_plural': 'Закрепления количественного оборудования',
                'constraints': [models.UniqueConstraint(fields=('equipment', 'employee'), name='uniq_equipment_allocation')],
            },
        ),
    ]
