# Generated by Django 6.0.7 on 2026-07-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_accesspass_uniq_pass_account_by_type'),
        ('equipment', '0008_equipment_quantity_equipmenttype_accounting_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipment',
            name='uniq_equipment_inventory',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Учётный номер'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='inventory_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Учётный номер'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(condition=models.Q(('inventory_number', ''), _negated=True), fields=('inventory_number',), name='uniq_equipment_inventory'),
        ),
    ]
