# Generated by Django 6.0.7 on 2026-07-20 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_revert_quantity_accounting'),
        ('locations', '0004_historicalplace_place_type_place_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='locations.place', verbose_name='Размещение'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='place',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.place', verbose_name='Размещение'),
        ),
    ]
