# Generated by Django 6.0.7 on 2026-07-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_maintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='next_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='historicalequipment',
            name='next_maintenance_date',
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='regulation_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Регламент (снимок)'),
        ),
        migrations.AddField(
            model_name='maintenancerecorditem',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='maintenancerecorditem',
            name='from_regulation',
            field=models.BooleanField(default=False, verbose_name='Из регламента'),
        ),
        migrations.AddField(
            model_name='maintenancerecorditem',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменена'),
        ),
        migrations.CreateModel(
            name='MaintenanceRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('period_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Периодичность, мес.')),
                ('on_demand', models.BooleanField(default=False, verbose_name='По потребности')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Отменён (архив)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulations', to='equipment.equipment')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulations', to='equipment.equipmenttype')),
            ],
            options={
                'verbose_name': 'Регламент ТО',
                'verbose_name_plural': 'Регламенты ТО',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentMaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_planned_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата ТО')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Отменён для экземпляра')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='equipment.equipment')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='equipment.maintenanceregulation')),
            ],
            options={
                'verbose_name': 'План ТО оборудования',
                'verbose_name_plural': 'Планы ТО оборудования',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='regulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='equipment.maintenanceregulation'),
        ),
        migrations.CreateModel(
            name='MaintenanceRegulationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('work', 'Работы'), ('material', 'Материалы')], max_length=10, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='equipment.maintenanceregulation')),
            ],
            options={
                'verbose_name': 'Позиция регламента ТО',
                'verbose_name_plural': 'Позиции регламента ТО',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='maintenanceregulation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('equipment__isnull', True), ('equipment_type__isnull', False)), models.Q(('equipment__isnull', False), ('equipment_type__isnull', True)), _connector='OR'), name='regulation_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='equipmentmaintenanceplan',
            constraint=models.UniqueConstraint(fields=('equipment', 'regulation'), name='uniq_equipment_regulation_plan'),
        ),
    ]
