# Generated by Django 6.0.7 on 2026-07-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_equipmenttype_allows_license'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcustomfield',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Дополнительное поле оборудования', 'verbose_name_plural': 'Дополнительные поля оборудования'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttypefield',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Реквизит типа оборудования', 'verbose_name_plural': 'Реквизиты типа оборудования'},
        ),
        migrations.AddField(
            model_name='equipmentcustomfield',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='equipmenttypefield',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='historicalequipmentcustomfield',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
