# Generated by Django 6.0.7 on 2026-07-30 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_alter_equipmentcustomfield_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'ordering': ['name'], 'verbose_name': 'Вид оборудования', 'verbose_name_plural': 'Виды оборудования'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttypefield',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Реквизит вида оборудования', 'verbose_name_plural': 'Реквизиты типа оборудования'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.equipmenttype', verbose_name='Вид оборудования'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='equipment_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.equipmenttype', verbose_name='Вид оборудования'),
        ),
    ]
