# Generated by Django 6.0.7 on 2026-08-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0021_equipmenttypefile_equipment_type_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmenttypefile',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Общий файл вида оборудования', 'verbose_name_plural': 'Общие файлы вида оборудования'},
        ),
        migrations.AddField(
            model_name='equipmenttypefile',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
