# Generated by Django 6.0.7 on 2026-07-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Лого')),
                ('inn', models.CharField(blank=True, max_length=32, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=32, verbose_name='КПП')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название компании')),
                ('domain', models.CharField(blank=True, max_length=255, verbose_name='Домен компании')),
                ('ip_allowlist', models.JSONField(blank=True, default=list, verbose_name='Ограничение доступа по IP')),
                ('storage_mode', models.CharField(choices=[('local', 'Локально'), ('s3', 'S3')], default='local', max_length=10, verbose_name='Хранилище файлов')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компания',
            },
        ),
    ]
