# Generated by Django 6.0.7 on 2026-07-10 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_backup_enabled',
            field=models.BooleanField(default=False, verbose_name='Автокопирование включено'),
        ),
        migrations.AddField(
            model_name='company',
            name='auto_backup_retention',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Хранить последних копий'),
        ),
        migrations.AddField(
            model_name='company',
            name='auto_backup_time',
            field=models.TimeField(default=datetime.time(3, 0), verbose_name='Время автокопирования'),
        ),
    ]
