# Generated by Django 6.0.7 on 2026-07-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_ip_allowlist_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='kpp',
        ),
    ]
