# Generated by Django 6.0.7 on 2026-07-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_rename_backup_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='transport_number_prefix',
            field=models.CharField(default='TS', max_length=16, verbose_name='Префикс номеров транспорта'),
        ),
        migrations.AddField(
            model_name='company',
            name='transport_number_seq',
            field=models.PositiveIntegerField(default=0, verbose_name='Счётчик номеров транспорта'),
        ),
    ]
