# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_company_transport_number_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_backup_timezone',
            field=models.CharField(default='UTC', max_length=64, verbose_name='Часовой пояс автокопий'),
        ),
    ]
