# Generated by Django 6.0.7 on 2026-07-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_company_auto_backup_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='device_snapshot_enabled',
            field=models.BooleanField(default=False, verbose_name='Сбор слепков устройств при акцепте'),
        ),
    ]
