# Generated by Django 6.0.7 on 2026-07-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_company_device_snapshot_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_upload_mb',
            field=models.PositiveIntegerField(default=20, verbose_name='Максимальный размер файла (МБ)'),
        ),
    ]
