# Generated by Django 6.0.7 on 2026-08-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_company_max_upload_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='anonymize_after_months',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Автообезличивание уволенных через, месяцев'),
        ),
    ]
