# Generated by Django 6.0.7 on 2026-08-03 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_company_anonymize_after_months'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdnDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('consent', 'Согласие на обработку ПДн'), ('policy', 'Политика обработки ПДн'), ('regulation', 'Положение в области обработки ПДн')], max_length=12, verbose_name='Вид документа')),
                ('source_mode', models.CharField(choices=[('link', 'Ссылка'), ('file', 'Файл')], max_length=4, verbose_name='Способ задания')),
                ('source_url', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на документ')),
                ('is_current', models.BooleanField(default=True, verbose_name='Текущая версия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='storage.storedfile', verbose_name='Файл документа')),
            ],
            options={
                'verbose_name': 'Документ по обработке ПДн',
                'verbose_name_plural': 'Документы по обработке ПДн',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'is_current'], name='company_pdn_kind_3f0548_idx')],
            },
        ),
    ]
