# Generated by Django 6.0.7 on 2026-08-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_pdndocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='background_journal_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Журнал фоновых задач просмотрен'),
        ),
    ]
