# Generated by Django 6.0.7 on 2026-08-12 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_company_background_journal_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='notify_window_end',
            field=models.TimeField(default=datetime.time(21, 0), verbose_name='Отправлять уведомления до'),
        ),
        migrations.AddField(
            model_name='company',
            name='notify_window_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Отправлять уведомления с'),
        ),
        migrations.AddField(
            model_name='company',
            name='notify_window_timezone',
            field=models.CharField(default='UTC', max_length=64, verbose_name='Часовой пояс окна уведомлений'),
        ),
    ]
