# Generated by Django 6.0.7 on 2026-07-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(choices=[('local', 'Локально'), ('s3', 'S3')], max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('migration_status', models.CharField(choices=[('none', '—'), ('in_progress', 'Копируется'), ('done', 'Завершено'), ('error', 'Ошибка')], default='none', max_length=15)),
                ('migration_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
