# Generated by Django 6.0.7 on 2026-07-19 19:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0010_alter_accesspass_uniq_pass_account_by_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                ('is_written_off', models.BooleanField(default=False, verbose_name='Признак списания')),
                ('written_off_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата списания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTool',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                ('is_written_off', models.BooleanField(default=False, verbose_name='Признак списания')),
                ('written_off_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата списания')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Инструмент',
                'verbose_name_plural': 'historical Инструменты',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalToolCustomField',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tools.tool')),
            ],
            options={
                'verbose_name': 'historical Дополнительное поле инструмента',
                'verbose_name_plural': 'historical Дополнительные поля инструмента',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ToolCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='tools.tool')),
            ],
            options={
                'verbose_name': 'Дополнительное поле инструмента',
                'verbose_name_plural': 'Дополнительные поля инструмента',
            },
        ),
        migrations.CreateModel(
            name='ToolMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('add', 'Приход'), ('write_off', 'Списание'), ('assign', 'Закрепление'), ('unassign', 'Открепление')], max_length=10, verbose_name='Тип движения')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee', verbose_name='Сотрудник')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='tools.tool')),
            ],
            options={
                'verbose_name': 'Движение инструмента',
                'verbose_name_plural': 'Движения инструмента',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ToolAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_allocations', to='employees.employee', verbose_name='Сотрудник')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='tools.tool')),
            ],
            options={
                'verbose_name': 'Закрепление инструмента',
                'verbose_name_plural': 'Закрепления инструмента',
                'constraints': [models.UniqueConstraint(fields=('tool', 'employee'), name='uniq_tool_allocation')],
            },
        ),
    ]
