# Generated by Django 6.0.7 on 2026-07-20 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_accesspass_storage_place_and_more'),
        ('locations', '0004_historicalplace_place_type_place_employees_and_more'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolallocation',
            options={'verbose_name': 'Размещение инструмента', 'verbose_name_plural': 'Размещения инструмента'},
        ),
        migrations.RemoveConstraint(
            model_name='toolallocation',
            name='uniq_tool_allocation',
        ),
        migrations.AddField(
            model_name='toolallocation',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tool_allocations', to='locations.place', verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='toolmovement',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='toolallocation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tool_allocations', to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddConstraint(
            model_name='toolallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('tool', 'employee'), name='uniq_tool_allocation_employee'),
        ),
        migrations.AddConstraint(
            model_name='toolallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('place__isnull', False)), fields=('tool', 'place'), name='uniq_tool_allocation_place'),
        ),
        migrations.AddConstraint(
            model_name='toolallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('employee__isnull', False), ('place__isnull', True)), models.Q(('employee__isnull', True), ('place__isnull', False)), _connector='OR'), name='tool_allocation_exactly_one_target'),
        ),
    ]
