# Generated by Django 6.0.7 on 2026-07-20 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_historicalplace_place_type_place_employees_and_more'),
        ('tools', '0002_alter_toolallocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolmovement',
            name='storage_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.place', verbose_name='Склад'),
        ),
    ]
