# Generated by Django 6.0.7 on 2026-07-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_toolmovement_storage_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolmovement',
            name='kind',
            field=models.CharField(choices=[('add', 'Приход'), ('write_off', 'Списание'), ('assign', 'Закрепление'), ('unassign', 'Открепление'), ('transfer', 'Перемещение')], max_length=10, verbose_name='Тип движения'),
        ),
    ]
