# Generated by Django 6.0.7 on 2026-07-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_alter_toolmovement_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolcustomfield',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Дополнительное поле инструмента', 'verbose_name_plural': 'Дополнительные поля инструмента'},
        ),
        migrations.AddField(
            model_name='historicaltoolcustomfield',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='toolcustomfield',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
