# Generated by Django 6.0.7 on 2026-07-28 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_employeeassignment_object_kind'),
        ('tools', '0005_alter_toolcustomfield_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolmovement',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_movements', to='employees.employeeassignment', verbose_name='Закрепление'),
        ),
    ]
