# Generated by Django 6.0.7 on 2026-08-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_toolmovement_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltool',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
