# Generated by Django 6.0.7 on 2026-07-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_historicalbuilding_history_change_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplace',
            name='requires_pass',
            field=models.BooleanField(default=False, verbose_name='Требуется ключ/пропуск'),
        ),
        migrations.AddField(
            model_name='place',
            name='requires_pass',
            field=models.BooleanField(default=False, verbose_name='Требуется ключ/пропуск'),
        ),
    ]
