# Generated by Django 6.0.7 on 2026-07-20 06:41

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_accesspass_storage_place_and_more'),
        ('locations', '0003_historicalplace_requires_pass_place_requires_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplace',
            name='place_type',
            field=models.CharField(choices=[('workplace', 'Рабочее место'), ('storage', 'Место хранения')], default='workplace', max_length=10, verbose_name='Тип места'),
        ),
        migrations.AddField(
            model_name='place',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='workplaces', to='employees.employee', verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('workplace', 'Рабочее место'), ('storage', 'Место хранения')], default='workplace', max_length=10, verbose_name='Тип места'),
        ),
        migrations.CreateModel(
            name='HistoricalPlace_employees',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.historicalplace')),
                ('place', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.place')),
            ],
            options={
                'verbose_name': 'HistoricalPlace_employees',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
