# Generated by Django 6.0.7 on 2026-07-27 11:08

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_building_room_requires_pass'),
        ('storage', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPlace_transport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'HistoricalPlace_transport',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalroom',
            name='parking_type',
            field=models.CharField(blank=True, choices=[('adjacent', 'Прилегающая парковка'), ('floor', 'Этаж-парковка')], default='', max_length=10, verbose_name='Вид парковки'),
        ),
        migrations.AddField(
            model_name='historicalroom',
            name='plan_file',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='storage.storedfile', verbose_name='План парковки'),
        ),
        migrations.AddField(
            model_name='place',
            name='transport',
            field=models.ManyToManyField(blank=True, related_name='parking_spots', to='transport.transport', verbose_name='Транспорт'),
        ),
        migrations.AddField(
            model_name='room',
            name='parking_type',
            field=models.CharField(blank=True, choices=[('adjacent', 'Прилегающая парковка'), ('floor', 'Этаж-парковка')], default='', max_length=10, verbose_name='Вид парковки'),
        ),
        migrations.AddField(
            model_name='room',
            name='plan_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.storedfile', verbose_name='План парковки'),
        ),
        migrations.AlterField(
            model_name='historicalplace',
            name='place_type',
            field=models.CharField(choices=[('workplace', 'Рабочее место'), ('storage', 'Место хранения'), ('parking_spot', 'Парковочное место')], default='workplace', max_length=12, verbose_name='Тип места'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('workplace', 'Рабочее место'), ('storage', 'Место хранения'), ('parking_spot', 'Парковочное место')], default='workplace', max_length=12, verbose_name='Тип места'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('parking_type', 'floor')), fields=('building', 'floor'), name='uniq_floor_parking_per_building'),
        ),
        migrations.AddField(
            model_name='historicalplace_transport',
            name='history',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.historicalplace'),
        ),
        migrations.AddField(
            model_name='historicalplace_transport',
            name='place',
            field=models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.place'),
        ),
        migrations.AddField(
            model_name='historicalplace_transport',
            name='transport',
            field=models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.transport'),
        ),
    ]
