# Generated by Django 6.0.7 on 2026-07-27 07:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0012_employeeduplicatedismissal'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('period_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Периодичность, мес.')),
                ('on_demand', models.BooleanField(default=False, verbose_name='По потребности')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Отменён (архив)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Регламент ТО транспорта',
                'verbose_name_plural': 'Регламенты ТО транспорта',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивный')),
                ('mileage_unit', models.CharField(choices=[('km', 'По километрам'), ('motohours', 'По моточасам')], default='km', max_length=10, verbose_name='Учёт пробега')),
                ('gibdd_registration', models.BooleanField(default=True, verbose_name='Регистрация в ГИБДД')),
            ],
            options={
                'verbose_name': 'Тип транспорта',
                'verbose_name_plural': 'Типы транспорта',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation_name', models.CharField(blank=True, max_length=255, verbose_name='Регламент (снимок)')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Проведено')),
                ('next_planned_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего ТО')),
                ('prior_planned_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата на момент ТО')),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Пробег/моточасы')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('regulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='transport.maintenanceregulation')),
            ],
            options={
                'verbose_name': 'Запись о ТО транспорта',
                'verbose_name_plural': 'Записи о ТО транспорта',
                'ordering': ['performed_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('work', 'Работы'), ('material', 'Материалы')], max_length=10, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('from_regulation', models.BooleanField(default=False, verbose_name='Из регламента')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Отменена')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transport.maintenancerecord')),
            ],
            options={
                'verbose_name': 'Позиция ТО транспорта',
                'verbose_name_plural': 'Позиции ТО транспорта',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRegulationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('work', 'Работы'), ('material', 'Материалы')], max_length=10, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transport.maintenanceregulation')),
            ],
            options={
                'verbose_name': 'Позиция регламента ТО транспорта',
                'verbose_name_plural': 'Позиции регламента ТО транспорта',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=255, verbose_name='Учётный номер')),
                ('is_written_off', models.BooleanField(default=False, verbose_name='Признак списания')),
                ('written_off_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата списания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport', to='employees.employee', verbose_name='Сотрудник')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport', to='transport.transporttype', verbose_name='Тип транспорта')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='maintenanceregulation',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulations', to='transport.transport'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='transport.transport'),
        ),
        migrations.CreateModel(
            name='HistoricalTransportCustomField',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transport', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.transport')),
            ],
            options={
                'verbose_name': 'historical Дополнительное поле транспорта',
                'verbose_name_plural': 'historical Дополнительные поля транспорта',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TransportCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='transport.transport')),
            ],
            options={
                'verbose_name': 'Дополнительное поле транспорта',
                'verbose_name_plural': 'Дополнительные поля транспорта',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransportFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='transport.transport')),
                ('value_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.storedfile')),
            ],
            options={
                'verbose_name': 'Значение реквизита транспорта',
                'verbose_name_plural': 'Значения реквизитов транспорта',
            },
        ),
        migrations.CreateModel(
            name='TransportFieldFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('stored_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.storedfile')),
                ('field_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='transport.transportfieldvalue')),
            ],
            options={
                'verbose_name': 'Файл реквизита транспорта',
                'verbose_name_plural': 'Файлы реквизита транспорта',
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransportFieldFile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stored_file', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='storage.storedfile')),
                ('field_value', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.transportfieldvalue')),
            ],
            options={
                'verbose_name': 'historical Файл реквизита транспорта',
                'verbose_name_plural': 'historical Файлы реквизита транспорта',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='maintenanceregulation',
            name='transport_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulations', to='transport.transporttype'),
        ),
        migrations.CreateModel(
            name='HistoricalTransport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=255, verbose_name='Учётный номер')),
                ('is_written_off', models.BooleanField(default=False, verbose_name='Признак списания')),
                ('written_off_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата списания')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee', verbose_name='Сотрудник')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transport_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.transporttype', verbose_name='Тип транспорта')),
            ],
            options={
                'verbose_name': 'historical Транспорт',
                'verbose_name_plural': 'historical Транспорт',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TransportTypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование реквизита')),
                ('value_type', models.CharField(choices=[('bool', 'Булево'), ('text', 'Текст'), ('int', 'Целое число'), ('float', 'Дробное число'), ('file', 'Файл'), ('list', 'Список')], max_length=10, verbose_name='Значение типа')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательность')),
                ('allow_multiple', models.BooleanField(default=False, verbose_name='Несколько файлов')),
                ('is_locked', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='transport.transporttype')),
            ],
            options={
                'verbose_name': 'Реквизит типа транспорта',
                'verbose_name_plural': 'Реквизиты типа транспорта',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='transportfieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='transport.transporttypefield'),
        ),
        migrations.CreateModel(
            name='HistoricalTransportFieldValue',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('value_file', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='storage.storedfile')),
                ('transport', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.transport')),
                ('field', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.transporttypefield')),
            ],
            options={
                'verbose_name': 'historical Значение реквизита транспорта',
                'verbose_name_plural': 'historical Значения реквизитов транспорта',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TransportTypeFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='transport.transporttypefield')),
            ],
            options={
                'verbose_name': 'Элемент списка реквизита транспорта',
                'verbose_name_plural': 'Элементы списка реквизита транспорта',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransportMaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_planned_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата ТО')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Отменён для экземпляра')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='transport.maintenanceregulation')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='transport.transport')),
            ],
            options={
                'verbose_name': 'План ТО транспорта',
                'verbose_name_plural': 'Планы ТО транспорта',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('transport', 'regulation'), name='uniq_transport_regulation_plan')],
            },
        ),
        migrations.AddConstraint(
            model_name='transport',
            constraint=models.UniqueConstraint(fields=('inventory_number',), name='uniq_transport_inventory'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceregulation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('transport__isnull', True), ('transport_type__isnull', False)), models.Q(('transport__isnull', False), ('transport_type__isnull', True)), _connector='OR'), name='transport_regulation_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='transportfieldvalue',
            constraint=models.UniqueConstraint(fields=('transport', 'field'), name='uniq_transport_field_value'),
        ),
    ]
