# Generated by Django 6.0.7 on 2026-07-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransport',
            name='parks_at_driver_address',
            field=models.BooleanField(default=False, verbose_name='Парковка на адресе водителя'),
        ),
        migrations.AddField(
            model_name='transport',
            name='parks_at_driver_address',
            field=models.BooleanField(default=False, verbose_name='Парковка на адресе водителя'),
        ),
    ]
