# Generated by Django 6.0.7 on 2026-07-30 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_historicaltransport_parks_at_driver_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transporttype',
            options={'ordering': ['name'], 'verbose_name': 'Вид транспорта', 'verbose_name_plural': 'Виды транспорта'},
        ),
        migrations.AlterModelOptions(
            name='transporttypefield',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Реквизит вида транспорта', 'verbose_name_plural': 'Реквизиты типа транспорта'},
        ),
        migrations.AlterField(
            model_name='historicaltransport',
            name='transport_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.transporttype', verbose_name='Вид транспорта'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport', to='transport.transporttype', verbose_name='Вид транспорта'),
        ),
    ]
