# Generated by Django 6.0.7 on 2026-08-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_transporttype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransport',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='transport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
