# Generated by Django 6.0.7 on 2026-08-04 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        ('transport', '0004_alter_historicaltransport_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportTypeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stored_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.storedfile')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_files', to='transport.transporttype')),
            ],
            options={
                'verbose_name': 'Общий файл вида транспорта',
                'verbose_name_plural': 'Общие файлы вида транспорта',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transport',
            name='type_files',
            field=models.ManyToManyField(blank=True, related_name='transport', to='transport.transporttypefile'),
        ),
    ]
