# Generated by Django 6.0.7 on 2026-08-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_transporttypefile_transport_type_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transporttypefile',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Общий файл вида транспорта', 'verbose_name_plural': 'Общие файлы вида транспорта'},
        ),
        migrations.AddField(
            model_name='transporttypefile',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
