# Generated by Django 6.0.7 on 2026-07-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Отдел')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employees/avatars/', verbose_name='Аватар')),
                ('is_employed', models.BooleanField(default=True, verbose_name='Работает')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
