# Generated by Django 6.0.7 on 2026-07-14 15:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSimCard',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sim_type', models.CharField(choices=[('sim', 'SIM'), ('esim', 'E-SIM')], default='sim', max_length=8, verbose_name='Тип')),
                ('phone_number', models.CharField(max_length=32, verbose_name='Номер телефона')),
                ('network_operator', models.CharField(blank=True, max_length=255, verbose_name='Оператор')),
                ('provider', models.CharField(blank=True, max_length=255, verbose_name='Поставщик услуг связи')),
                ('is_deactivated', models.BooleanField(default=False, verbose_name='Деактивирована')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee', verbose_name='Сотрудник')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical SIM-карта',
                'verbose_name_plural': 'historical SIM-карты',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_type', models.CharField(choices=[('sim', 'SIM'), ('esim', 'E-SIM')], default='sim', max_length=8, verbose_name='Тип')),
                ('phone_number', models.CharField(max_length=32, verbose_name='Номер телефона')),
                ('network_operator', models.CharField(blank=True, max_length=255, verbose_name='Оператор')),
                ('provider', models.CharField(blank=True, max_length=255, verbose_name='Поставщик услуг связи')),
                ('is_deactivated', models.BooleanField(default=False, verbose_name='Деактивирована')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_cards', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'SIM-карта',
                'verbose_name_plural': 'SIM-карты',
                'ordering': ['is_deactivated', '-created_at'],
            },
        ),
    ]
