# Generated by Django 6.0.7 on 2026-07-15 16:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_historicalsimcard_simcard'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=64, verbose_name='Учётный номер')),
                ('is_deactivated', models.BooleanField(default=False, verbose_name='Деактивирован')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.building', verbose_name='Здание')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='employees.employee', verbose_name='Сотрудник')),
                ('rooms', models.ManyToManyField(blank=True, related_name='+', to='locations.room', verbose_name='Помещения/зоны')),
            ],
            options={
                'verbose_name': 'Пропуск',
                'verbose_name_plural': 'Пропуска',
                'ordering': ['is_deactivated', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccessPass',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=64, verbose_name='Учётный номер')),
                ('is_deactivated', models.BooleanField(default=False, verbose_name='Деактивирован')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('building', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.building', verbose_name='Здание')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee', verbose_name='Сотрудник')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Пропуск',
                'verbose_name_plural': 'historical Пропуска',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAccessPass_rooms',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('accesspass', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.accesspass')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.historicalaccesspass')),
                ('room', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.room')),
            ],
            options={
                'verbose_name': 'HistoricalAccessPass_rooms',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
