# Generated by Django 6.0.7 on 2026-07-16 11:05
#
# SIM/пропуска становятся самостоятельными переиспользуемыми объектами: статус
# теперь = привязка к сотруднику (employee=NULL ⇒ деактивирован), поля
# is_deactivated/deactivated_at удаляются, номера/учётные номера — уникальны.
# Порядок операций важен: сначала делаем employee nullable, затем data-миграцией
# отвязываем ранее деактивированные записи и разруливаем дубли, и только после
# этого удаляем старые поля и вешаем UniqueConstraint.

import django.db.models.deletion
from django.db import migrations, models


def _dedupe(Model, field, skip_empty):
    """Оставляет по одной записи на значение (приоритет — привязанные к
    сотруднику, затем более новые), лишние удаляет. Данные на стенде тестовые —
    потеря дублей допустима (см. CHANGELOG)."""
    from collections import defaultdict

    groups = defaultdict(list)
    for obj in Model.objects.all():
        val = getattr(obj, field) or ""
        if skip_empty and not val.strip():
            continue
        groups[val].append(obj)
    for objs in groups.values():
        if len(objs) < 2:
            continue
        objs.sort(key=lambda o: (o.employee_id is not None, o.id), reverse=True)
        for extra in objs[1:]:
            extra.delete()


def migrate_status(apps, schema_editor):
    SimCard = apps.get_model("employees", "SimCard")
    AccessPass = apps.get_model("employees", "AccessPass")

    # Ранее деактивированные записи → отвязать (employee=NULL).
    SimCard.objects.filter(is_deactivated=True).update(employee=None)
    AccessPass.objects.filter(is_deactivated=True).update(employee=None)

    # Разрулить конфликты уникальности перед добавлением constraint.
    _dedupe(SimCard, "phone_number", skip_empty=False)
    _dedupe(AccessPass, "account_number", skip_empty=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_accesspass_buildings'),
        ('locations', '0001_initial'),
    ]

    operations = [
        # 1. Новые поля пропуска.
        migrations.AddField(
            model_name='accesspass',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='accesspass',
            name='type_pedestrian',
            field=models.BooleanField(default=False, verbose_name='Пеший'),
        ),
        migrations.AddField(
            model_name='accesspass',
            name='type_vehicle',
            field=models.BooleanField(default=False, verbose_name='Авто'),
        ),
        migrations.AddField(
            model_name='historicalaccesspass',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='historicalaccesspass',
            name='type_pedestrian',
            field=models.BooleanField(default=False, verbose_name='Пеший'),
        ),
        migrations.AddField(
            model_name='historicalaccesspass',
            name='type_vehicle',
            field=models.BooleanField(default=False, verbose_name='Авто'),
        ),
        # 2. employee → nullable / SET_NULL (нужно до отвязки в data-миграции).
        migrations.AlterField(
            model_name='accesspass',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes', to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_cards', to='employees.employee', verbose_name='Сотрудник'),
        ),
        # 3. Перенос данных: отвязать деактивированные + дедуп.
        migrations.RunPython(migrate_status, noop),
        # 4. Удаление старых полей статуса.
        migrations.RemoveField(model_name='accesspass', name='deactivated_at'),
        migrations.RemoveField(model_name='accesspass', name='is_deactivated'),
        migrations.RemoveField(model_name='historicalaccesspass', name='deactivated_at'),
        migrations.RemoveField(model_name='historicalaccesspass', name='is_deactivated'),
        migrations.RemoveField(model_name='historicalsimcard', name='deactivated_at'),
        migrations.RemoveField(model_name='historicalsimcard', name='is_deactivated'),
        migrations.RemoveField(model_name='simcard', name='deactivated_at'),
        migrations.RemoveField(model_name='simcard', name='is_deactivated'),
        # 5. Порядок сортировки.
        migrations.AlterModelOptions(
            name='accesspass',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пропуск', 'verbose_name_plural': 'Пропуска'},
        ),
        migrations.AlterModelOptions(
            name='simcard',
            options={'ordering': ['-created_at'], 'verbose_name': 'SIM-карта', 'verbose_name_plural': 'SIM-карты'},
        ),
        # 6. Уникальность.
        migrations.AddConstraint(
            model_name='accesspass',
            constraint=models.UniqueConstraint(condition=models.Q(('account_number', ''), _negated=True), fields=('account_number',), name='uniq_pass_account'),
        ),
        migrations.AddConstraint(
            model_name='simcard',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='uniq_sim_phone'),
        ),
    ]
