# Generated by Django 6.0.7 on 2026-07-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_accesspass_options_alter_simcard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspass',
            name='is_utilized',
            field=models.BooleanField(default=False, verbose_name='Утилизирован'),
        ),
        migrations.AddField(
            model_name='accesspass',
            name='object_type',
            field=models.CharField(choices=[('pass', 'Пропуск СКУД'), ('key', 'Ключ')], default='pass', max_length=8, verbose_name='Тип объекта'),
        ),
        migrations.AddField(
            model_name='accesspass',
            name='utilization_reason',
            field=models.CharField(blank=True, choices=[('utilized', 'Утилизирован'), ('handed', 'Передан арендодателю')], max_length=8, verbose_name='Причина утилизации'),
        ),
        migrations.AddField(
            model_name='accesspass',
            name='utilized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата утилизации'),
        ),
        migrations.AddField(
            model_name='historicalaccesspass',
            name='is_utilized',
            field=models.BooleanField(default=False, verbose_name='Утилизирован'),
        ),
        migrations.AddField(
            model_name='historicalaccesspass',
            name='object_type',
            field=models.CharField(choices=[('pass', 'Пропуск СКУД'), ('key', 'Ключ')], default='pass', max_length=8, verbose_name='Тип объекта'),
        ),
        migrations.AddField(
            model_name='historicalaccesspass',
            name='utilization_reason',
            field=models.CharField(blank=True, choices=[('utilized', 'Утилизирован'), ('handed', 'Передан арендодателю')], max_length=8, verbose_name='Причина утилизации'),
        ),
        migrations.AddField(
            model_name='historicalaccesspass',
            name='utilized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата утилизации'),
        ),
        migrations.AddField(
            model_name='historicalsimcard',
            name='is_utilized',
            field=models.BooleanField(default=False, verbose_name='Утилизирована'),
        ),
        migrations.AddField(
            model_name='historicalsimcard',
            name='utilized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата утилизации'),
        ),
        migrations.AddField(
            model_name='simcard',
            name='is_utilized',
            field=models.BooleanField(default=False, verbose_name='Утилизирована'),
        ),
        migrations.AddField(
            model_name='simcard',
            name='utilized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата утилизации'),
        ),
        migrations.AlterField(
            model_name='historicalaccesspass',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalsimcard',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
