# Generated by Django 6.0.7 on 2026-07-17 16:24

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_remove_accesspass_name'),
        ('locations', '0003_historicalplace_requires_pass_place_requires_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspass',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='+', to='locations.place', verbose_name='Места'),
        ),
        migrations.CreateModel(
            name='HistoricalAccessPass_places',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('accesspass', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.accesspass')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.historicalaccesspass')),
                ('place', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.place')),
            ],
            options={
                'verbose_name': 'HistoricalAccessPass_places',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
