# Generated by Django 6.0.7 on 2026-07-20 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_accesspass_uniq_pass_account_by_type'),
        ('equipment', '0011_revert_quantity_accounting'),
        ('locations', '0003_historicalplace_requires_pass_place_requires_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspass',
            name='storage_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.place', verbose_name='Место хранения'),
        ),
        migrations.AddField(
            model_name='historicalaccesspass',
            name='storage_place',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.place', verbose_name='Место хранения'),
        ),
        migrations.AddField(
            model_name='historicalsimcard',
            name='equipment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='historicalsimcard',
            name='storage_place',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.place', verbose_name='Место хранения'),
        ),
        migrations.AddField(
            model_name='simcard',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_cards', to='equipment.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='simcard',
            name='storage_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.place', verbose_name='Место хранения'),
        ),
    ]
