# Generated by Django 6.0.7 on 2026-07-27 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employeeduplicatedismissal'),
        ('transport', '0002_historicaltransport_parks_at_driver_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspass',
            name='pass_kind',
            field=models.CharField(choices=[('personal', 'Персональный'), ('transport', 'Транспортный')], default='personal', max_length=10, verbose_name='Вид пропуска'),
        ),
        migrations.AddField(
            model_name='accesspass',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes', to='transport.transport', verbose_name='Транспорт'),
        ),
        migrations.AddField(
            model_name='historicalaccesspass',
            name='pass_kind',
            field=models.CharField(choices=[('personal', 'Персональный'), ('transport', 'Транспортный')], default='personal', max_length=10, verbose_name='Вид пропуска'),
        ),
        migrations.AddField(
            model_name='historicalaccesspass',
            name='transport',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transport.transport', verbose_name='Транспорт'),
        ),
        migrations.AlterField(
            model_name='accesspass',
            name='type_vehicle',
            field=models.BooleanField(default=False, verbose_name='Личный авто'),
        ),
        migrations.AlterField(
            model_name='historicalaccesspass',
            name='type_vehicle',
            field=models.BooleanField(default=False, verbose_name='Личный авто'),
        ),
    ]
