# Generated by Django 6.0.7 on 2026-07-28 07:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('employees', '0013_accesspass_pass_kind_accesspass_transport_and_more'),
        ('locations', '0006_historicalplace_transport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('object_kind', models.CharField(choices=[('equipment', 'Оборудование'), ('sim', 'SIM-карта'), ('pass', 'Пропуск/Ключ'), ('tool', 'Инструмент')], max_length=10, verbose_name='Вид объекта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения сотрудника'), ('in_absentia', 'Закреплено заочно'), ('accepted', 'Закрепление подтверждено сотрудником'), ('rejected', 'Закрепление отклонено сотрудником')], max_length=12, verbose_name='Статус акцепта')),
                ('was_in_absentia', models.BooleanField(default=False, verbose_name='Было заочным')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата закрепления')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('return_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во к возврату')),
                ('device_snapshot', models.JSONField(blank=True, null=True, verbose_name='Слепок устройства')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Эпизод закрыт')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто закрепил')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто принял решение')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='employees.employee', verbose_name='Сотрудник')),
                ('return_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.place', verbose_name='Вернуть на')),
            ],
            options={
                'verbose_name': 'Закрепление за сотрудником',
                'verbose_name_plural': 'Закрепления за сотрудниками',
                'ordering': ['-assigned_at', '-id'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'closed_at'], name='employees_e_content_8c092a_idx'), models.Index(fields=['employee', 'closed_at'], name='employees_e_employe_498921_idx')],
            },
        ),
    ]
