# Generated by Django 6.0.7 on 2026-07-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_backfill_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeassignment',
            name='object_kind',
            field=models.CharField(choices=[('equipment', 'Оборудование'), ('sim', 'SIM-карта'), ('pass', 'Пропуск/Ключ'), ('tool', 'Инструмент'), ('transport', 'Транспорт')], max_length=10, verbose_name='Вид объекта'),
        ),
    ]
