# Generated by Django 6.0.7 on 2026-07-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_employeeassignment_object_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения сотрудника'), ('in_absentia', 'Закреплено заочно'), ('accepted', 'Закрепление подтверждено сотрудником'), ('rejected', 'Закрепление отклонено сотрудником'), ('cancelled', 'Передача отменена ответственным')], max_length=12, verbose_name='Статус акцепта'),
        ),
    ]
