# Generated by Django 6.0.7 on 2026-07-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_alter_employeeassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='decision_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к решению'),
        ),
    ]
