# Generated by Django 6.0.7 on 2026-07-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_employeeassignment_decision_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspass',
            name='object_type',
            field=models.CharField(choices=[('pass', 'Пропуск СКУД'), ('key', 'Ключ')], default='pass', max_length=8, verbose_name='Вид средства'),
        ),
        migrations.AlterField(
            model_name='historicalaccesspass',
            name='object_type',
            field=models.CharField(choices=[('pass', 'Пропуск СКУД'), ('key', 'Ключ')], default='pass', max_length=8, verbose_name='Вид средства'),
        ),
    ]
