# Generated by Django 6.0.7 on 2026-08-03 12:55

from django.db import migrations, models
from django.utils import timezone


def backfill_terminated_at(apps, schema_editor):
    """B51-R1. У уже уволенных на момент обновления даты увольнения нет —
    проставляем дату миграции. Так авто-обезличивание отсчитает срок с момента
    апдейта (даём честные N месяцев), а не сотрёт их задним числом сразу."""
    Employee = apps.get_model("employees", "Employee")
    Employee.objects.filter(is_employed=False, terminated_at__isnull=True).update(
        terminated_at=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_alter_accesspass_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обезличивания'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_anonymized',
            field=models.BooleanField(default=False, verbose_name='Обезличен'),
        ),
        migrations.AddField(
            model_name='employee',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.RunPython(backfill_terminated_at, migrations.RunPython.noop),
    ]
