# Generated by Django 6.0.7 on 2026-08-03 15:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_pdndocument'),
        ('employees', '0021_employee_anonymized_at_employee_is_anonymized_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('operator', 'Подтверждено оператором'), ('self', 'Подтверждено сотрудником')], max_length=8, verbose_name='Источник')),
                ('at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата согласия')),
                ('by_position', models.CharField(blank=True, max_length=255, verbose_name='Должность оператора')),
                ('by_name', models.CharField(blank=True, max_length=301, verbose_name='ФИО оператора')),
                ('device_snapshot', models.JSONField(blank=True, null=True, verbose_name='Слепок устройства')),
                ('documents', models.ManyToManyField(blank=True, related_name='+', to='company.pdndocument', verbose_name='Документы согласия')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Согласие на обработку ПДн',
                'verbose_name_plural': 'Согласия на обработку ПДн',
                'ordering': ['source'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'source'), name='uniq_employee_consent_source')],
            },
        ),
    ]
