# Generated by Django 6.0.7 on 2026-07-10 19:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивный')),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Тип лицензии',
                'verbose_name_plural': 'Типы лицензий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_retired', models.BooleanField(default=False, verbose_name='Признак утилизации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='equipment.equipment', verbose_name='Оборудование')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='licenses.licensetype', verbose_name='Тип лицензии')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='licenses.license')),
            ],
            options={
                'verbose_name': 'Дополнительное поле лицензии',
                'verbose_name_plural': 'Дополнительные поля лицензии',
            },
        ),
        migrations.CreateModel(
            name='HistoricalLicense',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_retired', models.BooleanField(default=False, verbose_name='Признак утилизации')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('equipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.equipment', verbose_name='Оборудование')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('license_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='licenses.licensetype', verbose_name='Тип лицензии')),
            ],
            options={
                'verbose_name': 'historical Лицензия',
                'verbose_name_plural': 'historical Лицензии',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LicenseTypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование реквизита')),
                ('value_type', models.CharField(choices=[('bool', 'Булево'), ('text', 'Текст'), ('int', 'Целое число'), ('float', 'Дробное число'), ('file', 'Файл')], max_length=10, verbose_name='Значение типа')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательность')),
                ('is_locked', models.BooleanField(default=False)),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='licenses.licensetype')),
            ],
            options={
                'verbose_name': 'Реквизит типа лицензии',
                'verbose_name_plural': 'Реквизиты типа лицензии',
            },
        ),
        migrations.CreateModel(
            name='LicenseFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to='licenses/fields/')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='licenses.license')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='licenses.licensetypefield')),
            ],
            options={
                'verbose_name': 'Значение реквизита лицензии',
                'verbose_name_plural': 'Значения реквизитов лицензии',
                'constraints': [models.UniqueConstraint(fields=('license', 'field'), name='uniq_license_field_value')],
            },
        ),
    ]
