# Generated by Django 6.0.7 on 2026-07-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_alter_licensefieldvalue_value_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallicense',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата утилизации'),
        ),
        migrations.AddField(
            model_name='license',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата утилизации'),
        ),
    ]
