# Generated by Django 6.0.7 on 2026-07-15 06:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_historicallicensecustomfield_and_more'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetypefield',
            name='allow_multiple',
            field=models.BooleanField(default=False, verbose_name='Несколько файлов'),
        ),
        migrations.AlterField(
            model_name='licensetypefield',
            name='value_type',
            field=models.CharField(choices=[('bool', 'Булево'), ('text', 'Текст'), ('int', 'Целое число'), ('float', 'Дробное число'), ('file', 'Файл'), ('list', 'Список')], max_length=10, verbose_name='Значение типа'),
        ),
        migrations.CreateModel(
            name='HistoricalLicenseFieldFile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('field_value', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='licenses.licensefieldvalue')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stored_file', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='storage.storedfile')),
            ],
            options={
                'verbose_name': 'historical Файл реквизита лицензии',
                'verbose_name_plural': 'historical Файлы реквизита лицензии',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LicenseFieldFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('field_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='licenses.licensefieldvalue')),
                ('stored_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.storedfile')),
            ],
            options={
                'verbose_name': 'Файл реквизита лицензии',
                'verbose_name_plural': 'Файлы реквизита лицензии',
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LicenseTypeFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='licenses.licensetypefield')),
            ],
            options={
                'verbose_name': 'Элемент списка реквизита лицензии',
                'verbose_name_plural': 'Элементы списка реквизита лицензии',
                'ordering': ['order', 'id'],
            },
        ),
    ]
