# Generated by Django 6.0.7 on 2026-07-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0007_seed_hardware_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallicense',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicallicensecustomfield',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicallicensefieldfile',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicallicensefieldvalue',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
