# Generated by Django 6.0.7 on 2026-07-20 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0008_alter_historicallicense_history_change_reason_and_more'),
        ('locations', '0004_historicalplace_place_type_place_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallicense',
            name='storage_place',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.place', verbose_name='Место хранения'),
        ),
        migrations.AddField(
            model_name='license',
            name='storage_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.place', verbose_name='Место хранения'),
        ),
    ]
