# Generated by Django 6.0.7 on 2026-07-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0012_cleanup_orphaned_field_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensecustomfield',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Дополнительное поле лицензии', 'verbose_name_plural': 'Дополнительные поля лицензии'},
        ),
        migrations.AlterModelOptions(
            name='licensetypefield',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Реквизит типа лицензии', 'verbose_name_plural': 'Реквизиты типа лицензии'},
        ),
        migrations.AddField(
            model_name='historicallicensecustomfield',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='licensecustomfield',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='licensetypefield',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
