# Generated by Django 6.0.7 on 2026-07-30 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0013_alter_licensecustomfield_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensetype',
            options={'ordering': ['name'], 'verbose_name': 'Вид лицензии', 'verbose_name_plural': 'Виды лицензий'},
        ),
        migrations.AlterField(
            model_name='historicallicense',
            name='license_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='licenses.licensetype', verbose_name='Вид лицензии'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='licenses.licensetype', verbose_name='Вид лицензии'),
        ),
        migrations.AlterField(
            model_name='licensetype',
            name='kind',
            field=models.CharField(choices=[('software', 'Программная'), ('hardware', 'Аппаратная')], default='software', max_length=10, verbose_name='Тип'),
        ),
    ]
