# Generated by Django 6.0.7 on 2026-08-04 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0015_alter_historicallicense_created_at_and_more'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseTypeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_files', to='licenses.licensetype')),
                ('stored_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.storedfile')),
            ],
            options={
                'verbose_name': 'Общий файл вида лицензии',
                'verbose_name_plural': 'Общие файлы вида лицензии',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='license',
            name='type_files',
            field=models.ManyToManyField(blank=True, related_name='licenses', to='licenses.licensetypefile'),
        ),
    ]
