# Generated by Django 6.0.7 on 2026-08-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0016_licensetypefile_license_type_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensetypefile',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Общий файл вида лицензии', 'verbose_name_plural': 'Общие файлы вида лицензии'},
        ),
        migrations.AddField(
            model_name='licensetypefile',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
