# Generated by Django 6.0.7 on 2026-08-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('backup', 'Резервное копирование'), ('maintenance', 'Напоминания о ТО'), ('anonymize', 'Обезличивание уволенных'), ('storage_migration', 'Перенос файлов хранилища'), ('notifications', 'Отправка уведомлений')], max_length=32)),
                ('status', models.CharField(choices=[('ok', 'Успешно'), ('error', 'Ошибка')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected', models.PositiveIntegerField(default=0)),
                ('detail', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Прогон фоновой задачи',
                'verbose_name_plural': 'Журнал фоновых задач',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', '-created_at'], name='core_backgr_job_e2b445_idx'), models.Index(fields=['-created_at'], name='core_backgr_created_f253a2_idx')],
            },
        ),
    ]
